### ISSUE TITLE
newbeercellar feedback

### ISSUE THREAD

**Issue by vegarpl** [atlefren/newbeercellar#1]
Ser fint ut.
Klarte ved et uhell å slette en øl når jeg skulle inn og redigere den da de to symbolene var veldig nærme hverandre.
Kunne også tenkt meg en kolonne for ølstil.
Sliter også med å logge meg inn på paden da den automatisk plukker "feil" gmailkonto. Da det er den jeg sist logget inn på nettleseren med.
Designet var pent og ryddig.
Finner ikke alt av bryggerier og øl, men det kommer vel mulighet for begge.
tommel opp for jobben :)

**Comment by atlefren** [comment]
Takk!
- Når det gjelder slette-knappen burde den kanskje være litt lengre vekk, evt spørre om bekreftelse evt gi angremulighet
- ad ølstil skulle jeg gjerne også hatt dette, problemet er at jeg ikke får disse dataene fra ratebeer, en muliget er jo å la brukere legge inn dette, men jeg vil jo ikke at alle skal selv kunne definere hvilken stil en gitt øl er, det må jo være en fasit.
- bryggerier/øl som ligger inne er basert på en dump fra ratebeer, så den skal i prinsippet inneholde alle data de har (med unntak av "retired"), men det kan være noe feil her også (enten på min import eller i dumpen fra ratebeer). Har tenkt på å se på mulighetene for å la brukere legge inn "egne øl", men da kan man fort få masser av duplikater etc, 

-google-innlogging: skal se på om det finnes noen enkel måte å tvinge google til å la deg velge hvilken konto du skal bruke. 

Oppretter "tasker" på det du spesifikt nevner her og "lukker" denne.
