### ISSUE TITLE
Make the cellar non-public by default

### ISSUE THREAD

**Issue by kriben** [atlefren/newbeercellar#5]
It is surprising to me that the cellars are public by default. Maybe make them non-public, or at least warn the user?

**Comment by atlefren** [comment]
@kriben Yes, agree with you there. The plan was to have the cellars public by default, but allow users to set them non-public in settings. I would argue that the contents of your beer cellar is rather non-sensitive, so public is a good default, but perhaps people disagree?

Somehow telling the users that their default cellar is public would be smart I guess.
